apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-ecr-updater
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: argocd-ecr-updater
